name = "colochess-backend"
main = "worker/src/index.ts"
compatibility_date = "2026-10-04"
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "colochess-db"
database_id = "a6f82506-0e5c-4cac-971b-a8ac0c1b34a7"

[vars]
ENVIRONMENT = "production"
EMAIL_FROM = "noreply@colochess.com"

# Optional Cloudflare Pages / Static Assets for the Admin Dashboard:
# [site]
# bucket = "./admin"
